### ISSUE TITLE
Feature request: Support 2FA

### ISSUE THREAD

**Issue by ubieberich** [bropat/ioBroker.eufy-security#1]
**Describe the bug**  
My eufy account has 2FA activated. The adapter only provides fields für User and password. 

**Screenshots & Logfiles**  
[log.log](https://github.com/bropat/ioBroker.eufy-security/files/5327823/log.log)

**Versions:**  
 - Adapter version: 0.0.1
 - JS-Controller version: 3.1.6
 - Node version: 12.18.3
 - Operating system: linux (Doker)

**Comment by bropat** [comment]
Hi ubieberich,

2FA is almost implemented. The login is already working as well as trusting ioBroker as "Trusted Device". I'm currently working on the token renewal.
As soon as it is stable enough i will release it.

**Comment by bropat** [comment]
> Hi ubieberich,
> 
> 2FA is almost implemented. The login is already working as well as trusting ioBroker as "Trusted Device". I'm currently working on the token renewal.
> As soon as it is stable enough i will release it.

In the meantime the push notifications aren't working anymore. The push notifications are the only way I have found to renew the token without human intervention. 
I'm investigating the issue with @JanLoebel [here](https://github.com/JanLoebel/eufy-node-client/issues/9).

**Comment by bropat** [comment]
@ubieberich 2FA is supported with version 0.0.2, but it still misses the renewal of the authentication token. This means that when the authentication token expires the verification code will be sent again and it must be entered again in the adapter to continue wo work.

**Comment by linuxq** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Can one get Version 0.02 already?                                                                                                                                                                                                                                                                                                                         Von: notifications@github.comGesendet: 16. November 2020 13:47An: ioBroker.eufy-security@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: Re: [bropat/ioBroker.eufy-security] 2FA not supported (#1)  
@ubieberich 2FA is supported with version 0.0.2, but it still misses the renewal of the authentication token. This means that when the authentication token expires the verification code will be sent again and it must be entered again in the adapter to continue wo work.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bropat** [comment]
@linuxq Version 0.0.2 isn't released. It will be published in the next days.

**Comment by bropat** [comment]
Version 0.0.2 with 2FA support was published.

**Note:** After successful authentication the token expires after 1 month and the renewal process is not implemented, so manual intervention is required!

**Comment by ubieberich** [comment]
Adapter works fine for me. No problem with the first 2FA login. Great job. Thanks.

Waiting till the token expires. Will then test the manual re-login.
