### ISSUE TITLE
Eufy Cloud: Critical security camera bug

### ISSUE THREAD

**Issue by sowoi** [bropat/ioBroker.eufy-security#134]
Maybe one or the other doesn't know it or it will be mentioned here soon as a supposed bug in connection with the iobroker plugin: There was a critical bug with the Eufy cameras today. Strangers could tap the video feed of others or take over the entire account, even if 2FA was enabled. 
Currently, my cameras are displayed as offline and I only learned by chance that there was this incident.
This makes this plugin even more important and I hope the developer manages to edit the devices to work without cloud. Thanks again to the developer for his work!

[Source](https://www.engadget.com/anker-eufy-security-camera-privacy-bug-130449901.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAHdpfX_SJhaI0Ac2G52zl2OEsOphJcKI9hBtNJLPC8YRWxlkHkvcNUwQ3kICdXhEhXXjO4sPvXMK_Oj9Dtdpr4AmNtIVxowRdWlc2yxdD0ZYtAXO0Rsffa2GP__4MgXCXu82dwAKyhf1z6qzZAgP7mjieiTvoMtvIUnZMq6oLOKl)

**Comment by bropat** [comment]
"Due to a software bug during our latest server upgrade at 4:50 AM EST today, a limited number (0.001%) of our users were able to access video feeds from other users’ cameras. Our engineering team recognized this issue at around 5:30 AM EST, and quickly got it fixed by 6:30AM EST.

The issue affected users at a small rate in the United States, New Zealand, Australia, Cuba, Mexico, Brazil, and Argentina. Users in Europe remain unaffected.

**Comment by bropat** [comment]
> I hope the developer manages to edit the devices to work without cloud

Unfortunately I have to disappoint you, because according to my reverse engineering status so far there are already some functionalities that only work with the cloud, such as:

Downloading a video event from the local station is only possible through the cloud, as the key to decrypt the video must be retrieved there.
