### ISSUE TITLE
Question: Local Livestream Clarification

### ISSUE THREAD

**Issue by wjbridge** [bropat/ioBroker.eufy-security#90]
Hey Bropat,

Awesome work on this eufy security extension! I know you are working on the wiki / docs but I had a question. The README file states that this supports
> Start livestream (hls; supports also local livestream)
> Stop livestream (hls)".

I have a Eufy wired 2k doorbell Wired Doorbell 2k (T8200). If you start the livestream, the livestream variable gives you a piece of a url in which you can use VLC to view. Is this livestream local or through the cloud (RTMP?). If this is through the local device directly, I would love to stream it continuously (almost like a poor mans RTSP stream). The only reason I have not done this is I am not sure if it is through the cloud (thus using my internet cap from my ISP). I have seen other Eufy extensions that will give you a URL but it is a cloud web address.

Thanks so much and sorry if this is a stupid question :).

**Comment by bropat** [comment]
Hi @wjbridge,

If the adapter establishes a successful connection to the station/device via P2P (visible through an info message in the log), then the stream is local, otherwise the stream via the cloud in RTMP is used as a fallback.
What I have seen so far from the Wired Doorbell, this allows a maximum P2P livestream of 10 minutes, then it disconnects.
